net(add, AGND, PT1-1)
net(add, AGND, PT2-1)
net(add, AGND, PT3-1)
net(add, AGND, PT4-1)
net(add, AGND, PT5-1)
net(add, AGND, PT6-1)
net(add, AGND, PT7-1)
net(add, AGND, PT8-1)

net(add, AGND, PL1-1)
net(add, AGND, PL2-1)
net(add, AGND, PL3-1)
net(add, AGND, PL4-1)
net(add, AGND, PL5-1)
net(add, AGND, PL6-1)
net(add, AGND, PL7-1)
net(add, AGND, PL8-1)

net(add, AGND, PR1-1)
net(add, AGND, PR2-1)
net(add, AGND, PR3-1)
net(add, AGND, PR4-1)
net(add, AGND, PR5-1)
net(add, AGND, PR6-1)
net(add, AGND, PR7-1)
net(add, AGND, PR8-1)

net(add, AGND, PB1-1)
net(add, AGND, PB2-1)
net(add, AGND, PB3-1)
net(add, AGND, PB4-1)
net(add, AGND, PB5-1)
net(add, AGND, PB6-1)
net(add, AGND, PB7-1)
net(add, AGND, PB8-1)
